### PR TITLE
Update to 4.0.0

### PR DESCRIPTION
**Pull request by tadeu**

### CODE REVIEW

**Comment by tadeu** [comment]
cc @edisongustavo @nicoddemus

**Comment by tadeu** [comment]
@jakirkham Just to let you know, I've rerendered on Windows using `conda-smithy 2.0.1`, and it is working fine! 👍

**Review by edisongustavo — APPROVED** [review]

**Comment by nicoddemus** [comment]
@edisongustavo please merge, you are the only maintainer at the moment. 😁

**Comment by edisongustavo** [comment]
I have the power!!!

**Pull request merged**
