### PR TITLE
Another attempt at 4.2.0

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #4 
Close #6

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/clcache This is ready for review/merge.

**Review by nicoddemus — APPROVED** [review]

**Review by tadeu — APPROVED** [review]
Nice!

**Comment by pitrou** [comment]
https://pypi.org/project/clcache-alt/ seems to be a newer version. The packager is https://github.com/rasjani .

**Comment by xhochy** [comment]
> https://pypi.org/project/clcache-alt/ seems to be a newer version.

This sadly only provides wheels and the source of the wheel is a bit unclear to myself.

**Comment by pitrou** [comment]
Then perhaps use the latest git changeset from https://github.com/frerich/clcache/ ?

**Comment by tadeu** [comment]
This 4.2.0 update seems fine already (thanks!), I think that the way to go now is to ask for a new official release from upstream?

**Comment by tadeu** [comment]
It looks like `clcache-alt` should be a new package in a new feedstock

**Comment by xhochy** [comment]
Upstream is archived, so there is no way to ask. Adding `clcache-alt` as a different feedstock sounds like the best choice.

**Comment by nicoddemus** [comment]
Agree!

**Comment by nicoddemus** [comment]
Actually seems a bit shady that `clcache-alt` only provides wheels and there's no link to the source code (it points to the archived `clcache` repository). I wouldn't install those wheels blindly hehehe.

**Pull request merged**
